### ISSUE TITLE
Top-Left Most Arrow Doesn't Expand sidebar

### ISSUE THREAD

**Issue by andrewgross** [notwaldorf/picasso#1] opened 2017-01-10 20:58 UTC
Hey,

Great extension, really appreciate you making this.

I noticed the top left arrow will not actually expand the sidebar for me.  This means I can no longer add/remove calendars.  When I clicked the arrow it rotated then disappeared, and now it will not come back. =/

### Before

![](https://captured-pics.s3.amazonaws.com/GX1MeHFams4UCONChn4RMwrN67xPUOrj0l.png)

### After

![](https://captured-pics.s3.amazonaws.com/bUKhRMWMyPXXXhHRvcQUs8MXzq8Z7wQq3v.png)

**Comment by notwaldorf** [comment] 2017-01-10 20:59
Hiya! That arrow doesn't expand the sidebar, it expands or collapses your all-day events.
I've completely nuked the sidebar! 💥 

Closing, as this is technically working as intended :)

**Closed by notwaldorf** 2017-01-10 20:59 UTC

**Comment by andrewgross** [comment] 2017-01-10 21:00
Fair enough.  In my browsing of it, I discovered the sidebar does still exist, kindof.  I can hover some grey squares near there and actually disable or enable a few of my calendars.  Obviously NBD since you don't want it there in the first place. Thanks again for the extension, I can just disable it if I need that functionality.

![](https://captured-pics.s3.amazonaws.com/O13A1wT2qdekMd88LnhKH7Yc81IQua32Yw.png)

**Comment by notwaldorf** [comment] 2017-01-10 21:01
(I'll work on trying to add the sidebar back!)
