### ISSUE TITLE
Bottoms of droopy letters getting cut off in event titles

### ISSUE THREAD

**Issue by thieman** [notwaldorf/picasso#3] opened 2017-01-10 23:47 UTC
The `g`s are having a bad time.

![image](https://cloud.githubusercontent.com/assets/1414305/21829615/2f66adb0-d765-11e6-8fe6-74c8c701de76.png)

**Comment by notwaldorf** [comment] 2017-01-11 00:13
Oof, I can't repro :/
<img width="148" alt="screen shot 2017-01-10 at 4 13 36" src="https://cloud.githubusercontent.com/assets/1369170/21830179/c5599578-d74f-11e6-9f54-d62263987a98.png">

**Comment by thieman** [comment] 2017-01-11 00:17
I'm on Chrome Windows, maybe it's a platform-specific issue. I can try it out on Chrome Mac in the morning.

**Comment by thieman** [comment] 2017-01-11 00:25
Fwiw, adding `line-height: normal !important` on the `<span>` holding that text fixes the issue. Not sure if that's useful debugging information or not. ¯\\\_(ツ)\_/¯

**Comment by notwaldorf** [comment] 2017-01-11 04:35
That `span` should already have `line-height: 1.2;`, which is...more. No?

**Comment by thieman** [comment] 2017-01-11 05:16
Some additional data from Chrome Windows:

1. Changing the window's zoom level to 90% displays the entire `g`, and changing it to 110% displays more of the `g` than the 100% zoom level, but not quite all of it.

2. Changing the line-height values to 1.21, 1.22, 1.23, or 1.24 do absolutely nothing at 100% zoom. Changing the line-height value to 1.25 suddenly makes the entire `g` show up. From some quick Googling it seems that Chrome may be doing some rounding down / int truncation on computed line-heights, possibly this truncation is bypassed when it has to calculate the line height itself via `normal`?

**Comment by notwaldorf** [comment] 2017-01-11 05:44
Ughhhhhhhh pixels, why are you the worsttttt.

Sounds cool, thanks so much for digging into it! I'll change it tomorrow :)

**Comment by thieman** [comment] 2017-01-11 14:00
Looks like my `g`s are fine on Chrome Mac regardless of what zoom level I choose. Windows font rendering problem maybe?

**Comment by mariusbalaban** [comment] 2017-01-12 13:17
Removing `overflow: hidden` from the `.cpchip` parent makes the droopy letters show completely. The same will happen with it if we make `.cpchip` `display: inline-block`. But any of this would be just a workaround for the font weirdness. 

Remove `"Segoe UI"` and will have full droopy letters, albeit with an uglier font. 

The entire problem is reproduced with this 

```
<html>

<head>
    <style>
    
        body {
            font-size: 12px;
            font-family: Roboto, "Helvetica -apple-system", BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
            -webkit-font-smoothing: antialiased;
        }
            #content {
                overflow: hidden;
            }

            #line {
                line-height: 1;
            }

            span {
                line-height: 1.2
            }
        </style>
</head>

<body>
    <div id="content">
        <span>gyj</span>
    </div>
</body>

</html>
```

**Comment by notwaldorf** [comment] 2017-01-18 20:12
Ugh, this sounds like I should file a Chrome bug :)

**Comment by mariusbalaban** [comment] 2017-01-19 08:21
Well, I've created one 🥇

**Comment by notwaldorf** [comment] 2017-01-23 19:35
@mariusbalaban can you link it in here, pretty please? I can find some people to look at it :)

**Comment by mariusbalaban** [comment] 2017-01-25 07:31
[Here it is ](https://bugs.chromium.org/p/chromium/issues/detail?id=685046&can=2&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by notwaldorf** [comment] 2017-01-26 18:46
Sweet! Looks like it's assigned! I'll keep an eye on it, but I'll close this issue for now since I'd really like Chrome to fix this! 🙏

**Closed by notwaldorf** 2017-01-26 18:46 UTC

**Comment by mariusbalaban** [comment] 2017-01-26 18:51
Yep, that's great.

**Comment by mariusbalaban** [comment] 2017-01-31 19:59
Well, it has been decided: [it's not a Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=685046#c7)
